version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
  build:
    commands:
      - cd Authentication
      - dotnet tool install -g Amazon.Lambda.Tools
      - export PATH="$PATH:/root/.dotnet/tools"
      - echo 'Lambda CLI installed'
      - dotnet restore
      - dotnet build --configuration Release
      - dotnet test --configuration Release --no-build
      - dotnet lambda package --configuration Release --output-package lambda.zip
      - dotnet lambda deploy-function Auth --region us-east-1
artifacts:
  files:
    - Authentication/lambda.zip
